[[datasets]]
name = "ego_motion"
path = "/Users/viktorjansson/Developer/Rust/cairn/data/nvidia_physical_dataset/egomotion.chunk_0000"
description = "ego_motion for the NVIDIA PhysicalAI Autonomous Vehicles dataset"
file_ext = ".egomotion.parquet"

[datasets.semantics]
timestamp = "timestamp"

[[datasets]]
name = "lidar"
path = "/Users/viktorjansson/Developer/Rust/cairn/data/nvidia_physical_dataset/lidar.chunk_0000"
description = "LiDAR for the NVIDIA PhysicalAI Autonomous Vehicles dataset"
file_ext = ".lidar_top_360fov.parquet"

[datasets.semantics]
timestamp = "timestamp_us"
